spring:
  application:
    name: hello-spring-cloud-config
  cloud:
    #将当前服务作为配置服务中心
    config:
      label: master
      server:
        #设置需要从哪个git平台读取配置文件
        git:
          uri: http://192.168.98.231/bingtangxin/spring-cloud-config.git
          search-paths: respo
          username: bingtangxin
          password: 12345678
  #将服务注册到服务链路追踪系统中
  zipkin:
    base-url: http://localhost:9411

  boot:
    admin:
      client:
        url: http://localhost:8084

server:
  port: 8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/